name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: SSH and echo to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ec2-18-217-95-150.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Hello from GitHub Actions!" > /tmp/github_message.txt
          echo "Deployment completed at $(date)" >> /tmp/github_message.txt
          cat /tmp/github_message.txt
